### ISSUE TITLE
 Opção na tela signup > Plano 

### ISSUE THREAD

**Issue by Elton-Coelho** [cleitonme/Whazing-SaaS.instalador#2]
Pensei em opção na tela signup
Plano 
ter opção com calculadora:

onde em minha empresa > Planos  
defini os valores:
Conexão
Atendente 
e o cliente defini a quantidade que precisa.
Calcular o valor do plano e criar a conta do cliente com a
quantidade que o cliente definiu de
Conexões
e
Atendente

**Comment by cleitonme** [comment]
concentrar no repositorio principal
